### ISSUE TITLE
add information about ground plate size

### ISSUE THREAD

**Issue by jerabaul29** [sparkfun/SparkFun_Swarm_Satellite_Arduino_Library#13]
I may be missing something, but I cannot find information about the ground plate size; can this be added on the webpage: https://www.sparkfun.com/products/19236 ? :)

**Comment by PaulZC** [comment]
Hi JR,

Thanks for the suggestion. Done. Also added to the hook-up guide:

https://learn.sparkfun.com/tutorials/satellite-transceiver-breakout---swarm-m138---hookup-guide#hardware-assembly

Best wishes,
Paul
