### ISSUE TITLE
Ground plane: is it waterproof

### ISSUE THREAD

**Issue by jerabaul29** [sparkfun/SparkFun_Swarm_Satellite_Arduino_Library#14]
Is the ground plane PCB waterproof? Or is there some naked metal that may rust? Can this be added on the project page https://www.sparkfun.com/products/19236 ?

**Comment by PaulZC** [comment]
Hi JR,

The ground plane has both grounded holes (holes with exposed tinned copper surround and through-hole plate) and plain through-holes (not grounded). This allows you to connect the ground plane to any surrounding metalwork, or not, depending on your needs.

The exposed finish is standard lead-free Hot Air Solder Levelled (HASL) plating. It will tarnish over time. You may wish to lacquer the board, with standard automotive spray lacquer, for longevity.

I'll add this information to the hook-up guide. Thanks for the suggestion!

Best wishes,
Paul
