### ISSUE TITLE
Python library?

### ISSUE THREAD

**Issue by openedhardware** [sparkfun/SparkFun_Swarm_Satellite_Arduino_Library#15]
### Subject of the issue
Just curious if you have a python library? I am going to use your modem with ESP32(micropython)

Thanks!

**Comment by nseidle** [comment]
I am confused by your avatar @openedhardware - Nothing about Raspberry Pi is open source hardware.

Please see the [hookup guide](https://learn.sparkfun.com/tutorials/satellite-transceiver-breakout---swarm-m138---hookup-guide). We have a python GUI that may get you started.
