### ISSUE TITLE
No serial communication with last updated version

### ISSUE THREAD

**Issue by GeoffreyJohnen** [sparkfun/SparkFun_Swarm_Satellite_Arduino_Library#34]
### No serial communication from ESP32 to Swarm board with last updated version
Hey everyone. With the last update, it seems I can't init the serial communication anymore from my ESP32 to the Sparkfun board. 
I'm using Pins 27 and 14 on the ESP32 Wrover. When I init, query $CS to check everything is working properly. (I know I could just query an update rate for the same purpose).
I have the two versions of the libraries on my platformio environment (two different projects). It doesn't get any reply from the Swarm with the new version, and works fine with the older. Same wiring, same code. 

To be noted as well, with the new version : the RX LED of the board stays powered up, not with the older.

Unfortunately, I don't have time to troubleshoot it more at that stage and I'll continue using the older version, but I'm just opening the issue to notify of the problem.

**Comment by PaulZC** [comment]
Hi Geoffrey (@GeoffreyJohnen ),

This doesn't sound like a library issue. More like a small difference between the way you have your platformio environments configured?

If you post your code here, we'll try and debug it for you.

Also, please make sure you have opened the split pad jumpers to isolate the RX and TX pins from the CH340. If the RX LED is illuminated, it makes me think that you still have at least one pad closed?

https://learn.sparkfun.com/tutorials/satellite-transceiver-breakout---swarm-m138---hookup-guide#hardware-hookup---breakout-pins

Best wishes,
Paul

**Comment by GeoffreyJohnen** [comment]
Hi Paul,

Indeed, after seeing that the problem couldn't be reproduced on different platforms, with same files, it makes me thing it is related to Platformio. 

Sorry about that.

Will close the issue.

**Comment by PaulZC** [comment]
No problem Geoffrey - thanks for the update,

It could be something to do with the TX and RX pin definition in your two environments? Maybe make sure you are using the exact same board definition in both? Just a guess though.

All the best,
Paul
