### ISSUE TITLE
Compilation error when using SoftwareSerial

### ISSUE THREAD

**Issue by oscarbaselga** [sparkfun/SparkFun_Swarm_Satellite_Arduino_Library#36]
### Error when calling begin() 
I am trying to code a sketch and when calling begin() for the M138 serial UART with a SoftwareSerial, compilation fails.

### Your workbench
* What platform are you using?
ESP32 T-Beam TTGO
* How does the code look like?
The sketch has been taken from Example1_getConfigurationSettings.ino, the single difference is the swarmSerial, which I have defined as a SoftwareSerial (this is a requirement for the future).

```
#include <SoftwareSerial.h>
#include <SparkFun_Swarm_Satellite_Arduino_Library.h>

SWARM_M138 mySwarm;

void setup()
{
  // Swarm Satellite Transceiver MicroMod Function Board PWR_EN
  #ifdef swarmPowerEnablePin
  pinMode(swarmPowerEnablePin, OUTPUT); // Enable modem power 
  digitalWrite(swarmPowerEnablePin, HIGH);
  #endif

  delay(1000);
  
  Serial.begin(115200);
  while (!Serial)
    ; // Wait for the user to open the Serial console
  Serial.println(F("Swarm Satellite example"));
  Serial.println();

  pinMode(4, INPUT);
  pinMode(0, OUTPUT);
  SoftwareSerial swarmSerial(4,0);
  swarmSerial.begin(115200);
  bool modemBegun = mySwarm.begin(swarmSerial); // Begin communication with the modem
  
  while (!modemBegun) // If the begin failed, keep trying to begin communication with the modem
  {
    Serial.println(F("Could not communicate with the modem. It may still be booting..."));
    delay(2000);
    modemBegun = mySwarm.begin(swarmSerial);
  }

  char *configSettings = new char[SWARM_M138_MEM_ALLOC_CS]; // Create storage for the configuration settings

  Swarm_M138_Error_e err = mySwarm.getConfigurationSettings(configSettings); // Get the settings
  
  if (err == SWARM_M138_SUCCESS)
  {
    Serial.print(F("The configuration settings are: "));
    Serial.println(configSettings);
  }
  else
  {
    Serial.print(F("Swarm communication error: "));
    Serial.print((int)err);
    Serial.print(F(" : "));
    Serial.println(mySwarm.modemErrorString(err)); // Convert the error into printable text
  }

  delete[] configSettings; // Free the storage
}

void loop()
{
  //Nothing to do here
}
```

### Steps to reproduce
1. Get the ESP32 boards including this URL in the Arduino IDE Preferences: https://dl.espressif.com/dl/package_esp32_index.json
2. From Manage Boards, install the Espressif ESP32 boards. It should appear the T-Beam option when selecting the target.
3. Copy the previous code in a new sketch.
4. Follow next hardware connections (ESP32->M138): 5V->Vin, GND->GND, 4->TX0, 0->RX1

### Expected behaviour
Everything compiles and the monitor serie shows the modem configurations.

### Actual behaviour
Next error when compiling:
```
undefined reference to 'SWARM_M138::begin(SoftwareSerial&)'
```

**Comment by PaulZC** [comment]
Hello Oscar (@oscarbaselga ),

Please see this forum issue:

https://forum.sparkfun.com/viewtopic.php?p=239375#p239375

Sadly, software serial is not going to work for you...

Best wishes,
Paul
