### ISSUE TITLE
SPX-19236

### ISSUE THREAD

**Issue by vangalvin** [sparkfun/SparkFun_Swarm_Satellite_Arduino_Library#8]
### Subject of the issue
Is the SPX-19236 an actual product or one that is being developed? 
when I follow the link i get a 404 not found

Will the board have its own ESP32 or similar processor or is it just a Serial/USB interface for the Swarm M138 modem?

**Comment by PaulZC** [comment]
Hi Boris (@vangalvin ),

The SPX-19236 is in development - the go-live will be in a few days. We released the library early so our colleagues and collaborators could start testing it.

The SparkFun Newsletter will keep you up to date with our product releases. please go to the [SparkFun Home Page](https://www.sparkfun.com/) and scroll down to the "STAY IN TOUCH WITH US" link.

I will leave this issue open until the product goes live.

Thank you for the interest,
Paul

**Comment by vangalvin** [comment]
Thanks @PaulZC ! I have been testing the library on the DEV kits and it seems to be working really well.

**Comment by PaulZC** [comment]
Thanks Boris,

Please be aware: if you are using the older Swarm Tile, the interface is slightly different. Most things will work but some things will not. The M138 does not use the “OP” command for example.

Please open a new issue if you see any strange behaviour or other weirdness.

Very best wishes,
Paul

**Comment by PaulZC** [comment]
Hi Boris (@vangalvin ),

SPX-19236 has just gone live:

https://www.sparkfun.com/products/19236

Closing...

Very best wishes,
Paul
